### ISSUE TITLE
is current `master` safe to use?

### ISSUE THREAD

**Issue by rtfeldman** [1602/elm-json-schema#42]
Thanks for making this library!

We were looking into it for testing some of our JSON Schemas, and discovered a bug in `3.0.0` that seems to be fixed on master. (The `additionalProperties` check resulting in validation errors if there were any properties *missing*, not just if there were *extra* properties.)

I wasn't sure what release plans were, so I was thinking about using the current work in progress on `master` in the interim (commit 7eb55c8d733b516a53e5b56b01c7c0462584099d). Is that a safe idea, or are things liable to break?

Thanks again!

**Comment by stoeffel** [comment]
that also supporta draft 4 right?

**Comment by 1602** [comment]
@rtfeldman I believe I could release what's in master after some cleanup. I'll find some time this weekend. By cleanup I mean that I don't quite like the shape of API currently exposed, functionality-wise everything should be fine and fully tested.

@stoeffel both draft 4 and draft 6 are supported, with one exception - remote refs are not supported, but as long as schema is built "in one piece" and all refs could be resolved synchronously - all fine.

**Comment by rtfeldman** [comment]
Oh wow, that would be fantastic! Thank you @1602!

**Comment by 1602** [comment]
Released 4.0.0.

I've decided to release things as is after some documentation cleanup. More substantial API changes would require more thinking and what is already there is good enough. If you have any feedback on API, suggestion on how would you improve it, please open a new issue, I'd be happy to help.

**Comment by stoeffel** [comment]
awesome thanks!
